export enum ErrosEnum {
  ENTITY_NODE_FOUND = 'ENTITY_NODE_FOUND',
  SOLICITATION_ALREADY_CLOSE = 'SOLICITATION_ALREADY_CLOSE',
  EMAIL_OR_PASSWORD_INCORRECT = 'EMAIL_OR_PASSWORD_INCORRECT',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  USER_CANNOT_BE_DELETED = 'USER_CANNOT_BE_DELETED'
}
